### PR TITLE
Implement i18n using vue-i18n

### PR DESCRIPTION
**Pull request by s-sasaki-0529**
Hi! I implemented i18n using vue-i18n! (issue #711)

I did the following

- Install and setup [vue-i18n](https://kazupon.github.io/vue-i18n/)
- Get the user's language from the window object
- Display English or Japanese based on the user's language

If other contributors want to add translations to other languages, all they have to do is to add them inside the `<i18n>` block.

スクリーンショット 2021-10-02 22 19 14

### CODE REVIEW

**Comment by alfg** [comment]
Thank you! I will review today and merge if all is good.

**Comment by alfg** [comment]
Hey @s-sasaki-0529, it looks good. However, it seems the tests have failed if you can address those before we merge.

Thanks!

**Comment by s-sasaki-0529** [comment]
@alfg Oh, There was no i18n injection into the unit tests, but it's fixed!

**Comment by alfg** [comment]
Thank you! Nice work!

**Pull request merged**
