### PR TITLE
 indian-protein-shake.json

### PR DESCRIPTION
**Pull request by M7hesh**
Tasty + Healthy!
Gotta try it.

### CODE REVIEW

**Review by alfg — CHANGES_REQUESTED** [review]
Hi, please use hyphens and lowercase only in the filenames. Also, please provide the referenced image. Thanks!

**Comment by M7hesh** [comment]
Done! #747

**Review by alfg — CHANGES_REQUESTED** [review]
Hi @M7hesh, can you fix the filename to use lowercase/hyphens only and include the image file?

**Comment by alfg** [comment]
Closing. Feel free to open another PR with suggested fixes. Thanks!

**Pull request closed without merging**
