### PR TITLE
Formatted ingredients and image to be in row on screen

### PR DESCRIPTION
**Pull request by pyorkman**
I noticed images were taking up nearly half of the page. I know this is a fun project, I felt it would be more realistic to have the image take up less of the page and the recipe and ingredients be more accessible to the reader upon page load. 
Styling for mobile was accounted for as well.

image

### CODE REVIEW

**Comment by alfg** [comment]
Thanks for this. I'll be able to check it out later tonight. Also, I noticed on your screenshot the "Similar Drinks" section is from a slightly older design. Can you sync up your fork so I can see the updated preview?

**Comment by pyorkman** [comment]
Turns out that was the merge conflict. I resolved the conflict so the newer Similar Drinks section is there instead of the old one.

**Comment by TobyAsE** [comment]
I like the idea!
I think there should be some sort of visual guide connecting the "Ingredients" and the image. In your screenshot both are just dangling around.
I would move the "Ingredients" up, so that there is a common line at the top. The rest is just me tinkering.
image

**Comment by alfg** [comment]
Yeah, also agreed on removing the `margin-top` from the ingredients section so it aligns with the image horizontally.

**Comment by pyorkman** [comment]
I can remove the margin-top above Ingredients and add a margin-bottom beneath the Contributed By, which was the reason I added the additional space. 
@TobyAsE , is there some other visual guide connecting the h4 and the image you had in mind other than having them in line with each other?

**Comment by TobyAsE** [comment]
I think that alone would increase the stability of the layout drastically.
I've opened #307 to tackle the other stuff that I noticed.

**Comment by alfg** [comment]
@pyorkman If you add the margin-top and margin-bottom fixes, we can go ahead and merge this in. We're still figuring out the visual guidelines, but I would like to use this updated design. :)

Also, do you think it's possible in the mobile view to display the image before the ingredients? I would like for the image to be mostly visible "above the fold" when viewing on a mobile device.

**Comment by alfg** [comment]
Thanks! I love the new layout. 👍 

I fixed some of the conflicts due to some recent changes around image locations.

**Pull request merged**
