### PR TITLE
The Quick Demise! 

### PR DESCRIPTION
**Pull request by dcorriveau**
A nice citrius-y drink just in time for Halloween!

### CODE REVIEW

**Review by alfg — CHANGES_REQUESTED** [review]
Hi, is it possible to provide an image that is not stretched?

**Comment by dcorriveau** [comment]
> Hi, is it possible to provide an image that is not stretched?

Not a problem! Let me know if this is a better image!

**Comment by alfg** [comment]
Thanks for fixing!

**Comment by dcorriveau** [comment]
> Thanks for fixing!

Not a problem!

**Pull request merged**
