### PR TITLE
Added Norwegian Glogg to the list of beverages. 

### PR DESCRIPTION
**Pull request by rohannair11**
This beverage is Norway's spin-off of the Swedish glogg.

### CODE REVIEW

**Review by alfg — CHANGES_REQUESTED** [review]
Hi, the recipe image and json file should have the same filename convention. 
`norwegian-glogg.json` and norwegian-glogg.jpg`, please. Thanks!

**Comment by rohannair11** [comment]
Hey sorry about that! I have changed the necessary files, please review. Also will this pr count towards my hacktoberfest contributions? I'm new to this actually.

**Review by alfg — CHANGES_REQUESTED** [review]
Please remove the old file too.

**Comment by rohannair11** [comment]
> Please remove the old file too.
Sorry, but which old file? I just renamed the wrong ones so that the titles of the json and jpeg files match.

**Comment by alfg** [comment]
In this PR, there are 3 files. One of the files are the first image you committed:
https://github.com/alfg/opendrinks/pull/1056/files#diff-93c17e58317834463e1008aefc22d0888cdd84cd699fa7e4465563e2ff4cc1ad

**Comment by rohannair11** [comment]
Deleted the previous jpeg

**Comment by alfg** [comment]
Thanks for fixing.

**Comment by rohannair11** [comment]
> Thanks for fixing.

No problem :-)

**Pull request merged**
