### PR TITLE
nannari sarabath recipe

### PR DESCRIPTION
**Pull request by saikoushalg**

### CODE REVIEW

**Comment by alfg** [comment]
Can you sync up your fork so only the new recipe shows up?

**Comment by saikoushalg** [comment]
> 
> 
> Can you sync up your fork so only the new recipe shows up?

i am sorry, i am  a beginner can you please tell how to do that?

**Comment by alfg** [comment]
Try following this guide to update your fork:
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by saikoushalg** [comment]
> 
> 
> Try following this guide to update your fork:
> https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork
> 
> Basically need to pull the latest changes from upstream (this repo) to your forked repo. That way the PR compares the diff changes correctly.

thankyou!

**Pull request closed without merging**
