### PR TITLE
Vodka Lemonade Punch

### PR DESCRIPTION
**Pull request by sdmmssa**

### CODE REVIEW

**Comment by sdmmssa** [comment]
I hope those changes fixed it. Let me know if anything else needs to be changed that I might have missed.

**Comment by sdmmssa** [comment]
Updated

**Comment by alfg** [comment]
600px should be the width, please.

**Comment by sdmmssa** [comment]
Changed width to 600 px. Didn't know you need it to be exactly 600x400 or if it could be less. Was trying to maintain the aspect ratio.

**Comment by alfg** [comment]
Maintaining the aspect ratio is fine. However, the original image is vertical. 600x400px should be a horizontal image. Please update the image if possible without stretching the image. If you need to, you can fill in the sides with white borders to maintain the ratio.

**Comment by sdmmssa** [comment]
Added the white space to maintain aspect ratio and sized to 600x400

**Comment by alfg** [comment]
Perfect! Thanks for the fix. I will update the image path after merge.

**Pull request merged**
