### PR TITLE
Add Stoned Gimlet

### PR DESCRIPTION
**Pull request by MakeItBack**

### CODE REVIEW

**Review by alfg — CHANGES_REQUESTED** [review]
Hi, one small request if you can name the recipe json and image filenames to be `stoned-gimlet.json` and `stoned-gimlet.json`. Thanks!

**Comment by MakeItBack** [comment]
> Hi, one small request if you can name the recipe json and image filenames to be `stoned-gimlet.json` and `stoned-gimlet.jpg`. Thanks!

Sure! Give me a few mins and I'll do it now

**Comment by MakeItBack** [comment]
OK - try that now

**Comment by alfg** [comment]
Hey, thanks for renaming them. However, you can remove the old files too before I can merge.

**Comment by MakeItBack** [comment]
> Hey, thanks for renaming them. However, you can remove the old files too before I can merge.

Sorry about that, yes I should have thought to tidy those up. Done

**Comment by alfg** [comment]
Looks good. Thanks for fixing!

**Pull request merged**
