### PR TITLE
Added Tequila Honeysuckle

### PR DESCRIPTION
**Pull request by Tash925**
Adding Tequila Honeysuckle drink.

### CODE REVIEW

**Comment by Tash925** [comment]
Hi, I added the jpg to src/assets/recipes/tequila-honeysuckle.jpg in my forked repo, is that format not correct? Thanks.

**Comment by alfg** [comment]
@Tash925 Right, I see the image committed, but it should be 600x400px (horizontal) instead of 400x600px.

**Comment by Tash925** [comment]
OK, I added a horizontal picture of the drink with the correct format. I hope this OK.

**Comment by alfg** [comment]
Perfect! Thanks for fixing. 💯

**Comment by Tash925** [comment]
Great thanks!

**Pull request merged**
