### PR TITLE
Added Dutchman's Daiquiri recipe

### PR DESCRIPTION
**Pull request by zzyzy**

### CODE REVIEW

**Comment by alfg** [comment]
Hi @zzyzy, 

Is it possible to resize the images to 600x400px?

**Comment by zzyzy** [comment]
Hi @alfg,

Will it be fine if it is stretched?

**Comment by alfg** [comment]
> Will it be fine if it is stretched?

Add white borders to the sides would be ok.

**Comment by zzyzy** [comment]
Hi, done! Please check.

**Comment by alfg** [comment]
Perfect! Thanks!

**Pull request merged**
