### PR TITLE
Added Ginger Lemon Tea

### PR DESCRIPTION
**Pull request by Lakshita2002**
A personal fav drink of mine!

### CODE REVIEW

**Comment by alfg** [comment]
Looks good. Thanks!

**Comment by Lakshita2002** [comment]
@alfg Could you please add `hacktoberfest-accepted` tag. Thanks!

**Comment by alfg** [comment]
Done. Thanks!

**Comment by Lakshita2002** [comment]
@alfg I actually learnt about json files through this PR. A great learning opportunity for beginners like me. Hail Open Source Community!

**Comment by alfg** [comment]
That's good to hear! Thanks for participating!

**Pull request merged**
