### PR TITLE
add new drink and image death in the gulf stream

### PR DESCRIPTION
**Pull request by nikolas-haug**
Hello,

I added a new drink json file for the drink 'death in the gulf stream'. 

I'm a newbie in the world of open source, so I really appreciate this open opportunity to learn more. 

Thank you!

### CODE REVIEW

**Review by alfg — CHANGES_REQUESTED** [review]
Hey @nikolas-haug, looks good. However, one small change if you can name the json and jpg filenames to match. Thanks!

**Comment by nikolas-haug** [comment]
No problem at all. Thanks for the feedback! Let me know if anything else needs adjustment.

**Comment by nikolas-haug** [comment]
Sorry, I realized that I didn't change the image path in the json file. I fixed that now and moved the changes up.

**Comment by alfg** [comment]
Looks good. Thanks for fixing!

**Pull request merged**
