### PR TITLE
Adds print option on recipe component

### PR DESCRIPTION
**Pull request by franciscoemanuel**
I've tried to implement it in a way that even if the component gets re-used, it only prints its content. Without losing the styles while printing. If there are any adjustments, or suggestions I'd love to hear it from you guys. #133

### CODE REVIEW

**Comment by alfg** [comment]
So I'm thinking instead of using an `iframe`, and a print button to directly launch the print prompt, I would like for it work a bit like:
1) Print button located below the tags
2) Clicking print button goes to a new view `/recipe/<drink-name>/print`
3) The new view is a printer-friendly page using minimal print-friendly css, where the user can use the native print function from the browser

It is similar to:
https://www.allrecipes.com/recipe/221893/vodka-martini-cocktail/
https://www.allrecipes.com/recipe/221893/vodka-martini-cocktail/print

Thoughts?

**Comment by franciscoemanuel** [comment]
Got it, working on it!

**Comment by franciscoemanuel** [comment]
done 👍

**Comment by alfg** [comment]
Awesome. Will check it out soon.

**Comment by alfg** [comment]
Nice and minimal. I love it! I just printed a recipe. :)

**Pull request merged**
