### PR TITLE
added a bourbon old fashioned recipe

### PR DESCRIPTION
**Pull request by brittanyjoiner15**

### CODE REVIEW

**Comment by brittanyjoiner15** [comment]
Just updated to new template and updated image of bourbon.

I'm a bit new to this - what do you do when there's a conflict?

**Comment by alfg** [comment]
The conflict mean it just found 2 different versions of the same lines on that file that are in conflict with each other. You can use the web editor here, or fix them locally and check them in.

So for example, if you click the "Resolve conflicts" button below, you'll see this in the affected file:
```
<<<<<<< master
        "1 1/2 ounces bourbon",
        "1 tablespoon fresh lime juice",
        "1/2 cup light ginger beer, such as Fever-Tree Naturally Light",
        "1 fresh mint sprig",
        "1 lime slice"
=======
        {
            "quantity": "1 1/2",
            "measure": "ounces",
            "ingredient": "bourbon"
        },
        {
            "quantity": "1",
            "measure": "tablespoon",
            "ingredient": "fresh lime juice"
        },
        {
            "quantity": "1/2",
            "measure": "cup",
            "ingredient": "light ginger beer, such as Fever-Tree Naturally Light"
        },
        {
            "quantity": "1",
            "measure": "",
            "ingredient": "fresh mint sprig"
        },
        {
            "quantity": "1",
            "measure": "",
            "ingredient": "lime slice"
        }
>>>>>>> master
```

There seems to be 2 copies of the same ingredients, but with a different format. This is because we updated the JSON format for the recipe ingredients yesterday.

The easiest way to fix would be to just "clean up" the file with the correct formatting and remove the other conflicting lines:
```
        {
            "quantity": "1 1/2",
            "measure": "ounces",
            "ingredient": "bourbon"
        },
        {
            "quantity": "1",
            "measure": "tablespoon",
            "ingredient": "fresh lime juice"
        },
        {
            "quantity": "1/2",
            "measure": "cup",
            "ingredient": "light ginger beer, such as Fever-Tree Naturally Light"
        },
        {
            "quantity": "1",
            "measure": "",
            "ingredient": "fresh mint sprig"
        },
        {
            "quantity": "1",
            "measure": "",
            "ingredient": "lime slice"
        }
```

Hope that helps.

**Comment by brittanyjoiner15** [comment]
Okay i am really confused now... i tried making that change but it still shows a conflict. I've actually cloned the new code for that file from [here](https://github.com/alfg/opendrinks/blob/master/src/recipes/bourbon-mule.json) and its still saying there's a conflict?

**Comment by alfg** [comment]
Looks like you cleared up most of it. There's a small part that needs to be removed/edited:
```
<<<<<<< master
}
=======
}
>>>>>>> master
```

**Comment by brittanyjoiner15** [comment]
That's where I'm confused cause on my end lines 44-48 are blank, there's nothing there

**Comment by alfg** [comment]
It could be because the fork is not up to sync with upstream.

**Comment by brittanyjoiner15** [comment]
Ah, possibly - how do i do that?

**Comment by alfg** [comment]
Yeah, looks like it's behind by about 40 commits. So it's most likely due to changes or updates on your file that others have made (not your fault). And since the repo seems to be moving fast, it caught a conflict between the most up-to-date master of this repo, and yours.

You can sync your fork by adding an `upstream` first. This configures git to pull latest changes from this repo as a source:
https://help.github.com/en/articles/configuring-a-remote-for-a-fork

Then, you fetch the changes, and merge them into your fork/branch:
https://help.github.com/en/articles/syncing-a-fork

So ultimately, it's something like:
```
git remote add upstream https://github.com/alfg/opendrinks.git
git fetch upstream
git checkout master
git merge upstream/master
```

This will bring the latest changes from this repo into your fork.

**Comment by alfg** [comment]
Sometimes it's easiest to just use the Github web-editor to make the changes, but keeping a fork up to sync with remote also helps when you plan to add more PRs in the future to avoid possible conflicts.

**Comment by alfg** [comment]
I synced up the fork and fixed the conflicts. So it's good to merge now. Thanks!

**Comment by brittanyjoiner15** [comment]
Ah okay perfect! Thanks for fixing that!

**Pull request merged**
