### PR TITLE
Created Tequila Slammer

### PR DESCRIPTION
**Pull request by mythicmrmun**
Added Tequila slammer recipe

### CODE REVIEW

**Comment by mythicmrmun** [comment]
TequilaSlammer

**Comment by alfg** [comment]
Almost, can you try adding the image? If you are  doing this via Github's UI, you can use the "upload file" button while in the `src/recipes/img/` folder.

Capture

and make sure it's named: `tequila-slammer.jpg`. 

Thanks!

**Comment by mythicmrmun** [comment]
I think I got it this time. I uploaded the image to my fork, I was attempting to upload to the master before with no push access.
I resized the image to 600x400px and requested a review of the pull request. 
Checked the img filename matches the file.

**Comment by alfg** [comment]
Nice! Thank you!

**Pull request merged**
