### PR TITLE
Issue 725

### PR DESCRIPTION
**Pull request by strawberries73**
Added a drink and did some editing.

### CODE REVIEW

**Comment by luisbg** [comment]
This sounds delicious. I should try it one day.

Small note. You might want to capitalize the first letter of each ingredient. I see other recipes doing that.

I am not a maintainer, so this is just my personal advice and unrelated to this PR being approved or not. I think it should be approved anyway and somebody (even yourself) can fix this later.

**Comment by strawberries73** [comment]
I will do that, Thank you!

**Comment by alfg** [comment]
@strawberries73 Thanks for the addition and corrections! However, I can't merge until the conflict is fixed if you can check, please.

**Comment by strawberries73** [comment]
Conflict Resolved.  :)  I had to look up how to do that.

**Comment by alfg** [comment]
Thanks for fixing!

**Pull request merged**
