### PR TITLE
Added April Rain Cocktail

### PR DESCRIPTION
**Pull request by Sai-Adarsh**
Added April Rain Cocktail to src/recipes/
Happy Hacktoberfest!

### CODE REVIEW

**Comment by Sai-Adarsh** [comment]
@alfg done!

**Comment by alfg** [comment]
Ah, sorry, I meant revert the package-lock.json changes. This PR is trying to delete the file entirely.

**Comment by Sai-Adarsh** [comment]
> Ah, sorry, I meant revert the package-lock.json changes. This PR is trying to delete the file entirely.

Alright, done!

**Comment by alfg** [comment]
Thanks!

**Pull request merged**
