### PR TITLE
Washington apple recipe

### PR DESCRIPTION
**Pull request by tnoeding**
Added the Washington Apple drink recipe.

### CODE REVIEW

**Comment by tnoeding** [comment]
Sorry, not sure how I missed that. Fixed and pushed.
Thanks!

**Comment by alfg** [comment]
Is it possible to find a higher quality image around 600x400px in size?

**Comment by tnoeding** [comment]
Image updated.

**Comment by alfg** [comment]
Do you have an image without the stretching?

**Comment by tnoeding** [comment]
Added a different picture that should be better with scaling.

**Comment by alfg** [comment]
Perfect! Thanks!

**Pull request merged**
