### PR TITLE
apple-cider-margarita-receipe-added

### PR DESCRIPTION
**Pull request by iampk94**

### CODE REVIEW

**Review by alfg — CHANGES_REQUESTED** [review]
Hi, please resolve conflict and provide horizontal images 600x400 in size. Thanks!

**Comment by alfg** [comment]
There's 3 files in this PR, can you sync up your fork or remove the extra file? Thanks.

**Comment by iampk94** [comment]
> There's 3 files in this PR, can you sync up your fork or remove the extra file? Thanks.

hey @alfg i was done all the changes, and pushed only two files in this year

**Comment by alfg** [comment]
Thanks!

**Pull request merged**
