### PR TITLE
Beton

### PR DESCRIPTION
**Pull request by 4ndrej**
Beton - the 60's Prague variation to Gin-Tonic. Image included.

### CODE REVIEW

**Review by alfg — CHANGES_REQUESTED** [review]
Image is too large in filesize. Please convert to JPG 200KB max. Thanks.

**Comment by 4ndrej** [comment]
resized as requested.

**Comment by 4ndrej** [comment]
I am not sure whether you need some more changes.

**Comment by alfg** [comment]
Looks good. Thanks!

**Pull request merged**
