### PR TITLE
add(recipe): grandmas-apple-pie-ala-mode-moonshine

### PR DESCRIPTION
**Pull request by ansidev**

### CODE REVIEW

**Comment by alfg** [comment]
Hey, would it be possible to use a 600x400px (horizontal) image?

**Comment by ansidev** [comment]
> Hey, would it be possible to use a 600x400px (horizontal) image?

I've updated the new image!

**Comment by alfg** [comment]
Without the watermark if possible.

**Comment by ansidev** [comment]
> Without the watermark if possible.

I tried to find it but:
1. Most of the original image is horizontal or square images.
2. I take this image from the video, I respect the copyright from the author.

So if you are OK with a square image, I can replace it with another one.

**Comment by alfg** [comment]
Square is OK

**Comment by ansidev** [comment]
> Square is OK

I've updated the new square image.

**Comment by alfg** [comment]
Looks good. Thank you!

**Pull request merged**
