### PR TITLE
chocolatelassi.json

### PR DESCRIPTION
**Pull request by sunainasapna**
enjoy tasty and new chocolate lassi.

### CODE REVIEW

**Comment by sunainasapna** [comment]
can you tell me what changes should be made to make some failure checks succesful

**Comment by sunainasapna** [comment]
> Hi, seems to be missing the image to go along with this json?

hy, the error is of image?

**Comment by alfg** [comment]
> 
> 
> > Hi, seems to be missing the image to go along with this json?
> 
> hy, the only error is of image?

RIght, there should be a `src/assets/recipes/chocolatelassi.jpg` too.

**Comment by alfg** [comment]
Closing. Feel free to reopen with the added image. Thanks!

**Pull request closed without merging**
