### PR TITLE
134 display similar drinks ui

### PR DESCRIPTION
**Pull request by TobyAsE**
I have added the UI for the similar drinks.
While I were at it, I moved the print-button and the keywords to the top of the page, they where a bit lost right at the bottom, now they are in view as soon as the recipe is opened.
Since my working-branch is two days old by now, I merged the master into it and immediately screwed up as the keywords I moved in d14050e got changed by #214, but that got corrected in 1fcd984.

### CODE REVIEW

**Comment by alfg** [comment]
Thank you! Checking this out now.

**Comment by alfg** [comment]
Nice, it looks pretty good!

My only concern is the spacing between the recommended items. I really like the style of the bootstrap cards, if we can adopt something similar:
https://bootstrap-vue.js.org/docs/components/card

Also, when a drink has many keywords, it displays like this:
Capture
 
Maybe limit keywords?

Either way, thanks again for your amazing effort on this!

**Comment by TobyAsE** [comment]
I do really enjoy working on this project and I'm learning a lot. I've never worked with vue before or contributed to an open source project. This is really fun.

I'll take a look at the number of keywords and the spacing.
The vue-card would be a completely different style but that should be implemented easily.

**Comment by TobyAsE** [comment]
Added the spacing and limited number of keywords to 3 on the tile.
I like the current hover-effect, but if you @alfg prefer the vue-card-style I'd be happy to change the layout accordingly. But that'll have to wait till tomorrow...

**Comment by alfg** [comment]
No problem. Thanks for the other fixes. I'll go ahead and merge this one in. 

I like the vue-card style mostly cause it's a familiar UI with the other bootstrap components. But we can tinker with that later. 

Thanks!

**Pull request merged**
