### PR TITLE
Fixed typos in recipe list

### PR DESCRIPTION
**Pull request by aycer25**
Fixed various typos, as well as updated formatting on some lists.

### CODE REVIEW

**Comment by alfg** [comment]
Hey, thanks for the corrections! However, there seems to be a conflict before we can merge. Thanks.

**Comment by alfg** [comment]
Hi @aycer25, possible to fix the conflict so we can merge this?

**Comment by aycer25** [comment]
Resolved the conflict, apologies for the delay

**Review by alfg — APPROVED** [review]

**Comment by alfg** [comment]
Thanks for the corrections! Much appreciated! 👍

**Pull request merged**
