### PR TITLE
Create three-wise-men.json

### PR DESCRIPTION
**Pull request by aracnoid149**
This is a simple whiskey recipe called the three wise men.  the three wise men being Jim, Jack, and John.

### CODE REVIEW

**Comment by aracnoid149** [comment]
I am uploading the picture in a separate pull request

**Comment by aracnoid149** [comment]
I was unable to upload a picture, is there another way for me to upload it?

**Review by alfg — CHANGES_REQUESTED** [review]
Missing image

**Comment by aracnoid149** [comment]
I could not upload it.  it is attached here
three-wise-men

**Comment by alfg** [comment]
It must be added to the PR. Feel free to re-open if uploaded as a commit.

**Pull request closed without merging**
