### PR TITLE
Add Grog Recipe

### PR DESCRIPTION
**Pull request by voodoods**
See issue https://github.com/alfg/opendrinks/issues/633. 
Added recipe for Grog! Yarrrr! 🏴‍☠️

screenshot-localhost_8081-2019 10 29-20_24_25

### CODE REVIEW

**Comment by alfg** [comment]
Thank you!

**Comment by voodoods** [comment]
@alfg the PR doesn't seem to count for my Hacktoberfest progress. Can you please add a corresponding label "hacktoberfest" to this PR? Thank you!

Bildschirmfoto 2019-10-30 um 06 54 59

**Comment by alfg** [comment]
Hmm, it should count towards any open-source repo on Github, regardless of the tag.

**Comment by voodoods** [comment]
You're right, the label on the issue should be enough. Seems to be a delay in the progress view only. Nevermind :)

**Pull request merged**
