### PR TITLE
Thai tea with almond milk

### PR DESCRIPTION
**Pull request by miewliie**
Added my favorite drink.

### CODE REVIEW

**Review by alfg — CHANGES_REQUESTED** [review]
HI, is it possible to use a square or 600x400px image? Thanks.

**Comment by miewliie** [comment]
> HI, is it possible to use a square or 600x400px image? Thanks.

@alfg  Done ✅

**Comment by miewliie** [comment]
> > HI, is it possible to use a square or 600x400px image? Thanks.
> 
> @alfg Done ✅

**Comment by miewliie** [comment]
> HI, is it possible to use a square or 600x400px image? Thanks.

@alfg done, the size is possible with 600 × 418. Hope this is okay.

**Comment by alfg** [comment]
That works. Thank you.

**Pull request merged**
