### PR TITLE
Use bootstrap card for similar recipes

### PR DESCRIPTION
**Pull request by TobyAsE**
I implemented the `b-card`-design. It's looking okay, I guess. Any ideas on what to change?

### CODE REVIEW

**Comment by alfg** [comment]
Oh, wow, it looks really long vertically. Can you adjust it to 2 items per row? (still 4 items max, though). I'm liking the style of it though.

**Comment by TobyAsE** [comment]
I'll change that

**Comment by TobyAsE** [comment]
Closes #134 
I think this should achieve that the issue is closes once this PR is merged...

**Comment by alfg** [comment]
Pretty cool! Thanks. Eventually I would like to make the cards fully clickable, instead of the view recipe button. Thanks for this!

**Pull request merged**
