### PR TITLE
253 recipe validation

### LINKED ISSUE #253: Recipe Validation
As discussed in #50 a validator for submitted recipes would be a nice thing to have.

### PR DESCRIPTION
**Pull request by TobyAsE**
I've built a schema for the recipes and a simple validation-script. I think the script is pretty ugly but I have no idea what I'm doing there.
But it works™.
Can we somehow incorporate this into the github actions @alfg ?

Closes #253

### CODE REVIEW

**Comment by TobyAsE** [comment]
Btw, are keywords mandatory?

**Comment by TobyAsE** [comment]
If we implement these checks, every existing recipe would need at least one keyword. I think that is not the case at the moment (I will check later). To not break everything we should first make sure that this is fulfilled for every recipe.
After that is accomplished I think it would be a good idea to have at least one keyword mandatory.

**Comment by alfg** [comment]
Thanks! Checking this out now.

**Comment by TobyAsE** [comment]
When making keywords mandatory the following recipes throw errors:
```
Validation failed for jungle-bird.json!
data should have required property 'keywords'
Validation failed for mango-daiquiri.json!
data should have required property 'keywords'
Validation failed for manhattan.json!
data should have required property 'keywords'
Validation failed for masala-coke.json!
data should have required property 'keywords'
Validation failed for tea-ais.json!
data should have required property 'keywords'
```

I will add some meaningful keywords to them.

**Comment by TobyAsE** [comment]
Is there a convenient way to run prettier on the file? It doesn't check the file when running `npm run serve`, and I can't blame it, the file isn't used anywhere after all. I hacked around with the CLI of prettier, but that wasn't very satisfying.

**Comment by alfg** [comment]
What happens when you try `npm run lint`? I noticed the lint warnings via plugin from VSCode, which will use the prettier/eslint config.

**Comment by TobyAsE** [comment]
`npm run lint` does nothing for the file. I installed `dbaeumer.vscode-eslint` into VSCode and fixed the problems it told me. Those were different problems prettier told me about earlier though...

**Comment by alfg** [comment]
Ah, almost forgot about this! Thanks!

**Pull request merged**
