### PR TITLE
Fix typo error

### PR DESCRIPTION
**Pull request by ansidev**
- Trim trailing white spaces.

### CODE REVIEW

**Comment by alfg** [comment]
Hey, sorry this won't count towards Hacktoberfest as it goes with the 'low effort' rule.

**Comment by ansidev** [comment]
@alfg I don't care about this PR to be counted as a Hacktoberfest contribution! I can make other PR to other repositories!

Don't impose your thoughts on others!

**Comment by alfg** [comment]
That's fine. Just make sure to follow: https://hacktoberfest.digitalocean.com/resources/qualitystandards

**Comment by ansidev** [comment]
Hi @alfg, could you please check the email from me? Thank you very much!

**Comment by alfg** [comment]
Hey @ansidev, this PR won't be re-opened for the reasons above. It is invalid.

**Comment by ansidev** [comment]
> Hey @ansidev, this PR won't be re-opened for the reasons above. It is invalid.

Hey @alfg, I understand that the PR is invalid (based on the rule).

It's my mistake because I don't know Hacktoberfest updated their rules until you send me the link. I'm not a spammer. If I know the rule before, I'll not submit this PR. For other PRs I submitted to this repo, I followed the Contribution Guide.

Hacktoberfest team said that a PR that has the label `invalid` is a spammy PR. So I'm not eligible to receive the Hacktoberfest gift :(. I'm not requesting you to reopen this PR, but could you please remove the label `invalid`? Thank you very much!

**Comment by alfg** [comment]
Hey @ansidev, if you can submit another valid drink recipe or a bug fix, I'll remove the `invalid` label on this issue. I think that would be fair.

**Comment by ansidev** [comment]
> Hey @ansidev, if you can submit another valid drink recipe or a bug fix, I'll remove the `invalid` label on this issue. I think that would be fair.

Yes, I did it and you merged

https://github.com/alfg/opendrinks/pulls?q=is%3Apr+author%3Aansidev+is%3Aclosed

**Comment by alfg** [comment]
Yes, but for a new one, though to replace this PR.

**Comment by ansidev** [comment]
> Yes, but for a new one, though to replace this PR.

OK.

**Comment by ansidev** [comment]
@alfg I opened PR https://github.com/alfg/opendrinks/pull/1290. Please check!

**Comment by alfg** [comment]
Thanks for the submission. I've removed the `invalid` label.

**Comment by ansidev** [comment]
> Thanks for the submission. I've removed the `invalid` label.

Thank you very much!

**Pull request closed without merging**
