### PR TITLE
Calamity Jane Cocktail recipe

### PR DESCRIPTION
**Pull request by mbartlet**
Adding JSON recipe and thumbnail for Calamity Jane cocktail.

### CODE REVIEW

**Review by alfg — CHANGES_REQUESTED** [review]
Hi, please provide a higher quality image around 600x400px in size, in JPG format. Thanks.

**Comment by mbartlet** [comment]
The image is not exactly 600x400, will that be an issue? And apologies, I should have noticed all the other images were .jpg

**Review by alfg — CHANGES_REQUESTED** [review]
Sorry, almost missed this. Can you update so the filenames match? Also, the image should be 200KB max in size, please.

**Comment by mbartlet** [comment]
>Can you update so the filenames match?

I assume you meant make the basename's match, I've changed `calamity-jane-cocktail.jpg` to `calamity-jane.jpg` to match `calamity-jane.json`, and compressed the image so it is <200KB. 

I was using zorbatini as a reference which has `zorbatini.json` and `zorbatini-cocktail.jpg`, hence my naming error. Should I correct that cocktail as well?

**Comment by alfg** [comment]
Thanks, the filenames look good now. However, the `image`filename  in the json needs to be updated as well, otherwise it won't load. 

Also, no need to update the other file. I'll fix that in master later.

**Comment by mbartlet** [comment]
Good catch, that's fixed now

**Review by alfg — APPROVED** [review]

**Comment by alfg** [comment]
All good! Thanks for the fixes.

**Pull request merged**
