### PR TITLE
Create cold-brew-old-fashioned.json

### PR DESCRIPTION
**Pull request by Latonis**
Added a new recipe for a cold brew old fashioned

### CODE REVIEW

**Comment by Latonis** [comment]
@alfg have combined them! :)

**Comment by alfg** [comment]
Thank @Latonis. One more suggestion is if it's possible to provide an alternate image that shows more of the drink?

**Comment by Latonis** [comment]
Sure @alfg, added a clearer one and updated the recipe with the new file name.

**Comment by alfg** [comment]
Almost. 2 suggestions:
1) The filename of json and image should be the same. Lets keep it as `cold-brew-old-fashioned`.
2) Can you convert the PNG to JPG. The files izes for PNG images are too large. That way we can target 200KB.

**Comment by Latonis** [comment]
@alfg I think i've finally done it haha

**Comment by alfg** [comment]
Perfect! Thank you @Latonis!

**Pull request merged**
