### PR TITLE
Adding recipe Dagobah Slug Slinger

### PR DESCRIPTION
**Pull request by bibliofilo**
Thank you for this project!

### CODE REVIEW

**Review by alfg — CHANGES_REQUESTED** [review]
File dimensions are too big. Please resize.

**Comment by bibliofilo** [comment]
The file dimensions have been fixed, and set to 600x400 px below 200 kb.

**Review by alfg — CHANGES_REQUESTED** [review]
Filenames should have hyphens instead of underscore. Also the recipe is missing the json extension and filename is misspelled. Also, please provide a 600x400px (horizontal) image.

**Comment by bibliofilo** [comment]
Got it, sorry for the typos and thanks for the feedback

**Comment by bibliofilo** [comment]
It's been failing the tests and I'm not sure why. I'll just close to clear it from the pull requests.

**Comment by alfg** [comment]
Most likely due to the image source using underscores, instead of hyphens in the json file:
```
"image": "dagobah_slug_linger.jpg",
```

**Pull request closed without merging**
