### PR TITLE
Added new recipe: Painkiller cocktail 

### PR DESCRIPTION
**Pull request by VENNELA2132**

### CODE REVIEW

**Comment by VENNELA2132** [comment]
Please approve my workflow

**Review by alfg — CHANGES_REQUESTED** [review]
Please use hyphens instead of underscore in the filename. Also fix the image link in the json. Thanks.

**Comment by VENNELA2132** [comment]
I have committed the requested changes please merge my pull request

**Comment by alfg** [comment]
Currently there's 2 image files in this PR. There should only be one. Please rename the files to just `painkiller.jpg` and `painkiller.json`. Remove the old file.

**Comment by VENNELA2132** [comment]
I have committed the requested changes. Please accept my pull request.

**Pull request merged**
