### PR TITLE
feat(generic): Added Dark Theme and button to Switch theme

### PR DESCRIPTION
**Pull request by Torfab**

### CODE REVIEW

**Review by alfg — CHANGES_REQUESTED** [review]
Hi, seems the build failed due to some linting errors. Please check the `Files changed` tab for more info on the affected lines.

**Comment by Torfab** [comment]
> 
> 
> Hi, seems the build failed due to some linting errors. Please check the `Files changed` tab for more info on the affected lines.

it should be fixed now

**Comment by alfg** [comment]
Hi @Torfab, 

I like the idea of the dark theme. However, a few suggestions and fixes:
1) Instead of the button near the main logo, can we make something more subtle. I like the idea using a small toggle on the top-left corner of the page. Here's an example I found:
https://codepen.io/Createdbymatt/pen/MMggQX

2) When I switch to dark mode, I can't seem to switch back to light. I get the following error:
```
DOMException: Node.removeChild: The node to be removed is not a child of this node
```

3) The white borders in dark mode seem a little distracting. Can we use a gray or something that blends in with the dark theme? 

Thanks!

**Comment by alfg** [comment]
Also, Bootstrap-Vue seems to have the styled toggle component available:
https://bootstrap-vue.org/docs/components/form-checkbox

**Comment by Torfab** [comment]
i will work on it later today (EU time)

**Comment by Torfab** [comment]
I decided to spend a bit more time on this PR.
I covered all 3 points you asked me to change.
In particular:
* I decided to use an eye-candy custom made slider. In my opinion, the feeling of it is very better, it is configurable as well from slider.scss file.
* I couldn't place the slider on the top left corner without moving the whole page down or having bad side effect when the browser shrinks. So I decided to place it at the same level as the logo, on the far right, it seems natural to me.
* I decided to refactor how I hook the style and to refactor the hierarchy of scss file. In this way, in the future, it will be really easier to make new styles (adding them in themes.scss).

At the moment the only two themes are light and dark if we'll have future developments we have to think about another way to change them (selectbox?!?).
Until then I suggest to keep the nice slider.

**Comment by alfg** [comment]
That's looking pretty good. I really like the slider design and use of the css switch. However, if possible I would still prefer this on the top left corner and a bit smaller in size. I tried in devtools by moving it to the same scope as the `github-corner` just to preview with:
```
position: absolute;
left: 6px;
top: 6px;
```
image

Also, is it necessary to add `node-sass` and `sass-loader` to the project for the theme component? I would like to keep dependencies minimal if possible.

Great work so far! 👍

**Comment by Torfab** [comment]
> I couldn't place the slider on the top left corner without moving the whole page down or having bad side effect when the browser shrinks. So I decided to place it at the same level as the logo, on the far right, it seems natural to me.
As I said it is not a good idea to place it on the topleft side or the layout will suffer when shrinks, here there is a gif to visualize my concerns, note the overlap of the slider with the logo.
mVtO3JPCAm

and this is the actual behaviour

r6Ejzpqjbz

I really prefer that position, but in the end is up to you, I don't want to impose my taste on your project.

Same concept is about the size, in the slider.css the variable "--switch-toggle-size" handle the size of the whole component, use it to tune the scale as you please.

hLGcS5KMsx

I added a little transition delay to have a smoother feeling on theme change.
I removed sass dependencies, the css file is less tidy than with scss dialect but i can understand your dependencies concerns.

**Comment by alfg** [comment]
Thanks for the adjustments. What if we hide or move the toggle for the smaller sized widths?

**Comment by Torfab** [comment]
to be fair I prefer this version.
Hiding it means deny functionality on mobile or little screens, moving it would feel not consistent.
For reference, https://hacktoberfest.digitalocean.com/ placed the toggle on top right corner as well.

I suggest you to merge it as is, consider that the component with toggle logic is self-contained in "themeHandler.vue" so you can move it in the app layout later on

**Comment by alfg** [comment]
OK, all sounds good! We'll try this out. One minor request if you can revert the package-lock.json before I merge. 

Thanks for all the work you put into this!

**Review by alfg — APPROVED** [review]

**Comment by Torfab** [comment]
> 
> 
> OK, all sounds good! We'll try this out. One minor request if you can revert the package-lock.json before I merge so it's not in the changeset.
> 
> Thanks for all the work you put into this!

done in dca7962

**Comment by alfg** [comment]
Thank you, @Torfab!

**Pull request merged**
