### PR TITLE
detox-green-juice

### PR DESCRIPTION
**Pull request by aindrila2412**
Please check and make it acceptable for Hacktoberfest.

### CODE REVIEW

**Review by alfg — CHANGES_REQUESTED** [review]
There seems to be duplicate recipes with slightly different names.

**Review by alfg — CHANGES_REQUESTED** [review]
The recipe JSON goes into `src/recipes/` and images go into `src/assets/recipes/` folders respectively. Thanks.

**Comment by alfg** [comment]
If you can, try running locally to test changes.

**Comment by aindrila2412** [comment]
I'm closing this pull request. I will open another pull request with this recipe. I can do that right?

**Pull request closed without merging**
