### PR TITLE
Pomegranate lemon mint

### PR DESCRIPTION
**Pull request by bookish**
Hello, thank you for your help.  I hope I am doing this correctly.

### CODE REVIEW

**Comment by alfg** [comment]
Closing. Feel free to reopen with requested fixes.

**Comment by bookish** [comment]
Dear Mr. Guttierrez;
I am new to github and contributing.  I would like to fix the contribution I made to your open drinks website because I think that the website is a good idea. I have another drink that I wanted to contribute as well.  For now, is it possible to find out what exactly I need to change, and how I can change things in my pomegranate-lemon-mint.json file?  I thought I fixed everything so I am not sure what I can do.  Please let me know because I really want to fix it.  I tried to submit changes to bookish-patch-1 and bookish-patch-2 but I am not sure if I am doing this correctly.  Would it be easier to just delete everything and restart with a new file name?
Thank you for your help
Shelby
________________________________

**Comment by alfg** [comment]
Hi Shelby,

I'm glad you want to contribute! I'd be happy to help. Here's a few items that would need to be fixed in order for the pull request to merge:

1) The `pomegranate-lemon-mint` file should be named: `pomegranate-lemon-mint.json` and placed into the folder: `src/recipes/`. It also should be checked for valid JSON. You can use something like https://jsonlint.com to validate your JSON file.

2) The image file to go along with this recipe is missing. Please add the image file to: `src/assets/recipes/` and name it `pomegranate-lemon-mint.jpg`. Keep in mind the image must be 600px wide and 400px height if possible.

3) Add all these changes via git into your fork, as you have been. Then create another Pull Request with the fixed changes. 

Feel free to respond if you have any additional questions.

**Comment by bookish** [comment]
Hi Alfred,
I submitted changes ot pomegranate-lemon-mint.json.  Please let me know if further changes need to be made in order for it to be submitted.
Thank you,
Shelby

________________________________

**Comment by alfg** [comment]
Hi @bookish. I am not sure I'm seeing the updated changes. Were the changes committed?

**Pull request closed without merging**
