### PR TITLE
added sgroppino al limone

### PR DESCRIPTION
**Pull request by Guberlo**

### CODE REVIEW

**Review by alfg — CHANGES_REQUESTED** [review]
Hi, can you sync up the branch from master so it only shows the new recipe in this PR?

**Comment by Guberlo** [comment]
Do I just need to fetch and pull data from upstream?

**Comment by alfg** [comment]
Yeah, it's basically syncing up your fork from upstream:
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by Guberlo** [comment]
I've synced my fork with the upstream, following the instructions provided in the link.
I'm not 100% sure this solved the problem. Can you confirm?

**Comment by alfg** [comment]
Yep! That worked. Thanks!

**Pull request merged**
