### PR TITLE
lemo cointreau recipe

### PR DESCRIPTION
**Pull request by Matheusafonsouza**

### CODE REVIEW

**Comment by Matheusafonsouza** [comment]
@alfg review?

**Review by alfg — CHANGES_REQUESTED** [review]
Hey, can you resize without stretching the image? Also, please use a JPG image, instead of PNG. Thanks.

**Comment by Matheusafonsouza** [comment]
@alfg fixed!

**Comment by alfg** [comment]
Looks good. Thanks!

**Pull request merged**
