### PR TITLE
add Thai pokpok, github kalamell

### PR DESCRIPTION
**Pull request by kalamell**

### CODE REVIEW

**Review by alfg — CHANGES_REQUESTED** [review]
Please provide an image around 600x400px in size without the watermark. Also if you can revert the package-lock.json so it doesn't show in change diff.

**Comment by kalamell** [comment]
> Please provide an image around 600x400px in size without the watermark. Also if you can revert the package-lock.json so it doesn't show in change diff.

Thank you. I resize image from you recommend

**Comment by alfg** [comment]
Image is duplicated. Also, please remove `package-lock.json` from this PR. Thanks.

**Comment by kalamell** [comment]
> Image is duplicated. Also, please remove `package-lock.json` from this PR. Thanks.

Ok. Thank you

**Review by alfg — CHANGES_REQUESTED** [review]
Package-lock.json should be removed from the PR. Please revert it so it doesn't show here. Also remove the old jpg image.

**Comment by alfg** [comment]
Closing per inactivity. Feel free to re-open another PR with the suggested fixes. Thanks.

**Pull request closed without merging**
