### PR TITLE
fixed typos in word "separating"

### PR DESCRIPTION
**Pull request by flyfishingbarbara**
fixed typos in word "separating"

### CODE REVIEW

**Comment by alfg** [comment]
Thanks for the fix!

**Comment by flyfishingbarbara** [comment]
hi Alfred-
still learning github... i see above a commit to 'delete mexican mule'. how did that happen? did i create that 'delete mexican mule' commit? that's not what i intended to do. i want it to be included. and i believe on your site it is included. 
don't get it.
thanks for explaining!

**Comment by flyfishingbarbara** [comment]
you're welcome. very cool site. telling all my friends about it.
-b

**Comment by alfg** [comment]
Hi Barbara, 

I did the delete of the Mexican Mule image before the merge. Since I moved the location of the drink recipe images a while back, I think git was trying to add it back into the original location since the fork is probably out of date and not synced up. There's nothing you did wrong, but it is good practice to keep the fork synced up before doing another PR, especially since this repo is moving very fast. :)

I use this guide for syncing a fork:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

I hope that helps. Thanks for contributing and for telling your friends!
-Alfred

**Comment by flyfishingbarbara** [comment]
...Alfred - Aha...i was wondering how contributors keep up to date on their forked repos. Thanks for info and link, Alfred. I took a look and will try next time!
cheers!
-b

**Comment by flyfishingbarbara** [comment]
PS - i'm good at finding typos if you need more help...
-b

**Comment by alfg** [comment]
> 
> 
> PS - i'm good at finding typos if you need more help...
> -b

Ha! Being a contributor-based project, I'm sure there will always be typos. :)

**Pull request merged**
