### PR TITLE
Added Mangalorean Tea drink

### PR DESCRIPTION
**Pull request by Aniket-508**

### CODE REVIEW

**Review by alfg — CHANGES_REQUESTED** [review]
Hi, can you rename the image file to `mangolorean-tea.jpg` (adding hyphen) to match the json filename. Thanks.

**Comment by Aniket-508** [comment]
@alfg Can you check if its ok now?

**Comment by alfg** [comment]
Hey, just noticed the image seems low resolution. Possible to provide a better quality image?

**Comment by Aniket-508** [comment]
@alfg Can you check it now?

**Comment by alfg** [comment]
Looks good. Thanks!

**Pull request merged**
