### PR TITLE
Fix #882: Add json file for Strawberry Limeade recipe 

### LINKED ISSUE #882: Add a drink! 🍸
Add your drink recipes by forking and submitting a pull request.

Be sure to check out the [Contributing Guidelines ](https://github.com/alfg/opendrinks/blob/master/CONTRIBUTING.md )before submitting a pull request. :)

Happy hacking!

### PR DESCRIPTION
**Pull request by archi15**
I added a Json file for a drink recipe for Strawberry Limeade. Please review my PR  @alfg. Thanks!

### CODE REVIEW

**Review by alfg — CHANGES_REQUESTED** [review]
Hi, format looks good. However is it possible to find a better quality image? This one seems blurry. Thanks.

**Comment by archi15** [comment]
I had made the changes please see that. Thanks!

**Comment by archi15** [comment]
@alfg Please review my PR. Thanks!

**Review by alfg — CHANGES_REQUESTED** [review]
Hi, the image looks stretched. Please provide an image without adjusting the aspect ratio. Thanks!

**Comment by archi15** [comment]
@alfg I added a new image with no editing. Please check that. Thanks!

**Comment by alfg** [comment]
Do you have one without the watermarks across the image?

**Comment by archi15** [comment]
@alfg I added image. Please review that. Thanks!

**Comment by alfg** [comment]
Looks good. Thanks!

**Pull request merged**
